// Generated by gencpp from file common/motor.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_MOTOR_H
#define COMMON_MESSAGE_MOTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common
{
template <class ContainerAllocator>
struct motor_
{
  typedef motor_<ContainerAllocator> Type;

  motor_()
    : num(0)
    , PWM(0.0)  {
    }
  motor_(const ContainerAllocator& _alloc)
    : num(0)
    , PWM(0.0)  {
  (void)_alloc;
    }



   typedef uint16_t _num_type;
  _num_type num;

   typedef double _PWM_type;
  _PWM_type PWM;





  typedef boost::shared_ptr< ::common::motor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::motor_<ContainerAllocator> const> ConstPtr;

}; // struct motor_

typedef ::common::motor_<std::allocator<void> > motor;

typedef boost::shared_ptr< ::common::motor > motorPtr;
typedef boost::shared_ptr< ::common::motor const> motorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::motor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::motor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::motor_<ContainerAllocator1> & lhs, const ::common::motor_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.PWM == rhs.PWM;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::motor_<ContainerAllocator1> & lhs, const ::common::motor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::motor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::motor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcb8db8f718aced907ae4911d3282034";
  }

  static const char* value(const ::common::motor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfcb8db8f718aced9ULL;
  static const uint64_t static_value2 = 0x07ae4911d3282034ULL;
};

template<class ContainerAllocator>
struct DataType< ::common::motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/motor";
  }

  static const char* value(const ::common::motor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 num\n"
"# BCM coding : 5 6 12 13 16 19 20 21\n"
"float64 PWM\n"
;
  }

  static const char* value(const ::common::motor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::motor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.PWM);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::motor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::motor_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.num);
    s << indent << "PWM: ";
    Printer<double>::stream(s, indent + "  ", v.PWM);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_MOTOR_H
