# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from common/gesture.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class gesture(genpy.Message):
  _md5sum = "88d3ec4e2cf6db353d34286a6368badd"
  _type = "common/gesture"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 IMUnum
float64 EulerAngleX
float64 EulerAngleY
float64 EulerAngleZ"""
  __slots__ = ['IMUnum','EulerAngleX','EulerAngleY','EulerAngleZ']
  _slot_types = ['uint16','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       IMUnum,EulerAngleX,EulerAngleY,EulerAngleZ

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(gesture, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.IMUnum is None:
        self.IMUnum = 0
      if self.EulerAngleX is None:
        self.EulerAngleX = 0.
      if self.EulerAngleY is None:
        self.EulerAngleY = 0.
      if self.EulerAngleZ is None:
        self.EulerAngleZ = 0.
    else:
      self.IMUnum = 0
      self.EulerAngleX = 0.
      self.EulerAngleY = 0.
      self.EulerAngleZ = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_H3d().pack(_x.IMUnum, _x.EulerAngleX, _x.EulerAngleY, _x.EulerAngleZ))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 26
      (_x.IMUnum, _x.EulerAngleX, _x.EulerAngleY, _x.EulerAngleZ,) = _get_struct_H3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_H3d().pack(_x.IMUnum, _x.EulerAngleX, _x.EulerAngleY, _x.EulerAngleZ))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 26
      (_x.IMUnum, _x.EulerAngleX, _x.EulerAngleY, _x.EulerAngleZ,) = _get_struct_H3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H3d = None
def _get_struct_H3d():
    global _struct_H3d
    if _struct_H3d is None:
        _struct_H3d = struct.Struct("<H3d")
    return _struct_H3d
